"""Canonical library of 40 distributed-systems papers.

These are the grounding facts the Lead Architect cites when justifying design
decisions (PDF: \"Grounding: Referencing the 40 white papers to ensure the
design is theoretically sound\").  Each entry is keyed by a short id so
Decision.grounded_in can reference it.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Paper:
    id: str
    title: str
    authors: str
    topics: tuple[str, ...]
    contribution: str


PAPERS: dict[str, Paper] = {p.id: p for p in [
    Paper("gfs", "The Google File System",
          "Ghemawat, Gobioff, Leung",
          ("storage", "replication", "fault_tolerance"),
          "Blueprint for scalable, fault-tolerant distributed storage on commodity hardware."),
    Paper("gfs_retro", "GFS: Evolution on Fast-Forward",
          "Quinlan, Myrick",
          ("storage", "scalability"),
          "Retrospective: smaller chunks and distributed metadata avoid single-master bottleneck."),
    Paper("bigtable", "Bigtable: Distributed Storage for Structured Data",
          "Chang et al.",
          ("storage", "nosql", "timeseries"),
          "Sparse, multi-dimensional sorted map underpinning modern NoSQL."),
    Paper("dynamo", "Dynamo: Amazon's Highly Available Key-Value Store",
          "DeCandia et al.",
          ("storage", "availability", "consistent_hashing"),
          "Consistent hashing + vector clocks for eventual consistency at scale."),
    Paper("dynamo_avail", "Dynamo (Availability Focus)",
          "DeCandia et al.",
          ("availability", "quorum"),
          "Sloppy quorums favor write availability during partitions."),
    Paper("ceph", "Ceph: A Scalable, High-Performance File System",
          "Weil et al.",
          ("storage", "file_system"),
          "Decoupled metadata via CRUSH map for extreme file-system scaling."),
    Paper("cassandra", "Cassandra: A Decentralized Structured Storage System",
          "Lakshman, Malik",
          ("storage", "nosql", "decentralized"),
          "Dynamo distribution model + Bigtable data model; masterless writes."),
    Paper("cassandra_gossip", "Cassandra (Architecture Focus)",
          "Lakshman, Malik",
          ("gossip", "failure_detection"),
          "Gossip and failure detection survive whole-AZ loss with no manual intervention."),
    Paper("corfu", "CORFU: A Shared Log Design for Flash Clusters",
          "Malkhi et al.",
          ("storage", "log", "event_sourcing"),
          "Shared log as the single source of truth for an entire cluster."),
    Paper("aurora", "Amazon Aurora: Cloud-Native RDBMS",
          "Gupta et al.",
          ("database", "sql", "log_is_db"),
          "Log-as-database: offload log processing to storage; zero-lag read replicas."),
    Paper("snowflake", "Snowflake: Self-Tuning Elastic Cloud Data Warehouse",
          "Zukowski et al.",
          ("warehouse", "olap", "elasticity"),
          "Storage/compute separation gives elastic, isolation-friendly OLAP."),
    Paper("paxos", "Paxos Made Simple",
          "Lamport",
          ("consensus", "strong_consistency"),
          "Foundational consensus protocol for asynchronous systems."),
    Paper("raft", "In Search of an Understandable Consensus Algorithm",
          "Ongaro, Ousterhout",
          ("consensus", "leader_election"),
          "Raft: practical alternative to Paxos with explicit leader election."),
    Paper("raft_full", "Raft (Comprehensive)",
          "Ongaro, Ousterhout",
          ("consensus", "safety", "liveness"),
          "Full safety/liveness proofs prevent split-brain in multi-region failover."),
    Paper("chubby", "The Chubby Lock Service",
          "Burrows",
          ("locking", "coordination"),
          "Coarse-grained distributed locks and leader-election primitive."),
    Paper("chubby_lease", "Chubby (Implementation Details)",
          "Burrows",
          ("leases", "real_time"),
          "Leases manage client liveness for real-time delivery."),
    Paper("zookeeper", "ZooKeeper: Wait-Free Coordination",
          "Hunt et al.",
          ("coordination", "metadata"),
          "Coordination plane for Kafka/Solr-style clusters."),
    Paper("cap", "The CAP Theorem",
          "Brewer",
          ("cap", "tradeoffs"),
          "Fundamental trade-off between consistency, availability, partition tolerance."),
    Paper("swim", "The SWIM Gossip Protocol",
          "Gupta et al.",
          ("gossip", "membership"),
          "Scalable weakly-consistent process-group membership."),
    Paper("consul", "Consul: Distributed Service Discovery",
          "HashiCorp",
          ("service_discovery", "health_check"),
          "Gossip + Raft + health checks for dynamic service mesh."),
    Paper("spanner", "Spanner: Google's Globally-Distributed Database",
          "Corbett et al.",
          ("database", "global_consistency", "truetime"),
          "TrueTime enables externally-consistent global transactions."),
    Paper("mapreduce", "MapReduce: Simplified Data Processing",
          "Dean, Ghemawat",
          ("batch", "parallel"),
          "Functional programming model for massive parallel batch jobs."),
    Paper("mapreduce_fail", "MapReduce (Failure Recovery)",
          "Dean, Ghemawat",
          ("resilience", "retry"),
          "Task-level retry minimises cost of failure in spot-instance pipelines."),
    Paper("pregel", "Pregel: Large-Scale Graph Processing",
          "Malewicz et al.",
          ("graph", "vertex_centric"),
          "Vertex-centric model for distributed graph algorithms."),
    Paper("mesos", "Mesos: Platform for Fine-Grained Resource Sharing",
          "Hindman et al.",
          ("orchestration", "scheduling"),
          "Two-level scheduling lets multiple frameworks share one cluster."),
    Paper("borg_k8s", "Borg, Omega, and Kubernetes",
          "Burns et al.",
          ("orchestration", "declarative"),
          "Declarative configuration with control loops beats imperative scripting."),
    Paper("k8s_book", "Kubernetes Up and Running",
          "Burns, Beda, Hightower",
          ("orchestration", "pods", "deployments"),
          "Pods, ReplicaSets, Deployments as the atoms of modern architecture."),
    Paper("hive", "Apache Hive",
          "Thusoo et al.",
          ("warehouse", "sql"),
          "SQL abstraction over Hadoop for analyst-facing data warehouses."),
    Paper("kafka", "Kafka: Distributed Messaging for Log Processing",
          "Kreps et al.",
          ("messaging", "log", "event_driven"),
          "Pull-based partitioned log replaces push-based queues for streaming."),
    Paper("seda", "SEDA: Staged Event-Driven Architecture",
          "Welsh et al.",
          ("concurrency", "queues"),
          "Stages connected by queues scale to thousands of concurrent requests."),
    Paper("dapper", "Dapper: Large-Scale Distributed Tracing",
          "Sigelman et al.",
          ("observability", "tracing"),
          "Trace IDs follow a request across microservices for diagnosis."),
    Paper("tail", "The Tail at Scale",
          "Dean, Barroso",
          ("latency", "p99"),
          "Hedged/backup requests keep tail latencies bounded in large fan-outs."),
    Paper("e2e", "The End-to-End Argument in System Design",
          "Saltzer, Reed, Clark",
          ("design_principles", "placement"),
          "Push functions to system ends to reduce networking complexity."),
    Paper("datacenter_as_computer", "The Datacenter as a Computer",
          "Barroso, Hoelzle",
          ("warehouse_scale", "infrastructure"),
          "Treat the whole datacenter as one warehouse-scale machine."),
    Paper("fawn", "FAWN: Fast Array of Wimpy Nodes",
          "Andersen et al.",
          ("energy", "cost"),
          "Many low-power nodes can beat fewer big ones for energy/cost."),
    Paper("zebra_gc", "The Zebra Copying Garbage Collector",
          "McCloskey et al.",
          ("runtime", "gc"),
          "GC tuning to avoid stop-the-world pauses violating SLAs."),
    Paper("treadmarks", "TreadMarks: Distributed Shared Memory",
          "Keleher et al.",
          ("memory", "hpc"),
          "Distributed shared memory across commodity workstations."),
    Paper("lsm", "LSM-Tree: Log-Structured Merge-Tree",
          "O'Neil et al.",
          ("storage_engine", "write_heavy"),
          "Append-then-merge beats in-place B-tree updates for write-heavy workloads."),
    Paper("gfs_scale", "GFS (Scalability Focus)",
          "Ghemawat et al.",
          ("snapshot", "namespace"),
          "Master operations such as snapshotting and namespace management."),
    Paper("k8s_history", "Borg/Omega/Kubernetes (Historical)",
          "Burns et al.",
          ("gitops", "control_loop"),
          "Control loop is the central engine of declarative infrastructure."),
]}

assert len(PAPERS) == 40, f"expected 40 canonical papers, got {len(PAPERS)}"


def by_id(paper_id: str) -> Paper:
    return PAPERS[paper_id]


def by_topic(topic: str) -> list[Paper]:
    """Return all papers tagged with the given topic."""
    return [p for p in PAPERS.values() if topic in p.topics]
